config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :students
  resources :teachers
  resources :kudos
  # patch '/sessions/rest', to: 'sessions#reset_view_tracker'
  # get '/signup', to: 'users#new'
  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :kudos
    has_many :teachers, through: :kudos
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :kudos
    has_many :students, through: :kudos
     has_secure_password
    # validates :name, presence: true
    # validates :name, uniqueness: true
#   validates :password, length: { in: 2..10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :set_current_user

    # def set_current_user
    #     @current_user = User.find_by(id: session[:user_id])
    # end

    # private
    # def set_view_tracker
    #     session[:view_tracker] ||=3
    # end
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
    before_action :kudo_finder, only: [:show, :update, :destroy, :edit]
    
    def new
        
        @kudo = Kudo.new
        
    end

    def create
     kudo = Kudo.create(kudo_params)
     redirect_to "/students/#{kudo.student.id}"
    end

    def edit
        
    end
   
    def update
        @kudo.update(kudo_params)
         redirect_to teacher_path(@kudo.teacher)
    end

    def destroy
    #    byebug
         kudo = Kudo.find(params[:id])
        
        kudo.destroy
        redirect_to teacher_path(params[:teacher][:id])
        #  redirect_to teacher_path(@kudo)
    end 



    private
     def kudo_params
         params.require(:kudo).permit(:student_id,:teacher_id,:kudo)
    end

    def kudo_finder
        @kudo = Kudo.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    def create
        @teacher = Teacher.find_by(username: params[:username])
        # return head(:forbidden) unless @user.authenticate(params[:password])
        if @teacher && @teacher.authenticate(params[:password])
            session[:teacher_id] = @teacher.id
            redirect_to students_path
        else
            flash.now[:alert] = "Username or password is invalid"
            render action: "new"
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logout Successful"
        redirect_to login_path
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = Student.all
    end
    def show
        @student = Student.find(params[:id])
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def index 
        @teachers = Teacher.all
    end
    def show 
        @teacher = Teacher.find(params[:id])

    end
    def new 
        @teacher = Teacher.new
        @errors = flash[:errors]

    end

    def create
        @teacher = Teacher.create(teacher_params)
        if @teacher.valid?
            session[:teacher_id] = @teacher.id
            redirect_to @teacher
        else 
            flash[:errors] = @teacher.errors.full_messages
            redirect_to new_teacher_path
        end
    end


    private
    def teacher_params
        params.require(:teacher).permit(:teacher_name,:subject,:room,:username,:password,:password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @errors = flash[:errors]
        @user = User.new
        render :new
    end

    def create
        user_params = params.require(:user).permit(:username, :password )
        user = User.create(user_params)
        if user.valid?
        #keeping track of user with session
            session[:user_id] = user.id
            redirect_to students_path
        else  
            flash[:errors] = user.errors.full_messages 
            redirect_to signup_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kudos_helper.rb
module KudosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kudos/edit.erb
<div class="space-edit-form" >
</div >


<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
<h1>Edit a Kudos!</h1>
<p class="contagious">Kudos are contagious, so let's give one..<p>
<hr>

<%= link_to "Home", students_path,class:"home"%>

<%= form_with model: @kudo do |f| %>
    
    <%= f.label :student_id%>
    <%= f.collection_select :student_id, Student.all, :id, :name%>
     
       
   
  
    <br>
    <%= f.label :teacher_id%>
    <%= f.collection_select :teacher_id, Teacher.all, :id, :teacher_name%><br>
    

   
    <%= f.label :kudos %>
    <%= f.text_area :kudo ,size: "30x5"%>
  
   
    <br>
    
    <%=  f.submit "Edit Kudo",class:"button" %>
    
<% end %>
</div>

app/views/kudos/new.erb
<%= link_to "Home", students_path,class:"home"%>


<div class="space-new-form" >
</div >

<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
    <h1>Create a Kudos!</h1>

    <p class="contagious">Kudos are contagious, so let's give one..<p>
<hr>
   
        <%= form_with model: @kudo do |f| %>
    
        <%= f.label :student_id%>
        <%= f.collection_select :student_id, Student.all, :id, :name%>
        
        <br>
        <%= f.label :teacher_id%>
        <%= f.collection_select :teacher_id, Teacher.all, :id, :teacher_name%><br>
        
        <%= f.label  :kudos %>
        <%= f.text_area :kudo ,size: "30x5" %><br>
        
        <%=  f.submit "Create Kudo",class:"button" %>
    <% end %>

    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kudo1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:ital@1&family=Lobster&family=Lora:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@100" rel="stylesheet">
  </head>

  <body>
  <%# <% if @current_user %> 
        <%# 👏 <%=@current_user.username%>  
        <%# <% else %> 
        <%# <%= link_to "Sign Up", "/signup"%> 
        <%# <%= link_to "Log in ", "/login"%> 

        <%# <%end%>
    <%= yield %>
  </body>
</html>

app/views/students/index.erb
<div class="font">
<nav class="navbar">
    <ul class="flex">
        
        
    
        
       
    </ul>
</nav>
<div class="space">
    <p> Kudos for students can create a continuous loop of positivity that spreads good vibes throughout the classroom.<p>
</div>

<div class="container-space">
    <div class="click">
        <h2>Click here to see a list of our Students<h2>
    </div>
</div>


    <% @students.each do |student| %>
    <div class="students-link" >
     <%= link_to student.name, student_path(student)  %><br></div>
    <%end%>
</div>

<br>

 <%= button_to "Create Kudos" , new_kudo_path, :method => "get",class:"button1"%>

<%# ☞ <%= link_to "Create a Kudos", new_kudo_path %>
<%# ☞ <%= link_to "Edit a Kudos", edit_kudo_path %> 



    <footer>
        <p>Kelsey Dickson</p>
    </footer>

</div>

app/views/students/show.erb
<%= link_to "Home", students_path,class:"home"%>


<div class="space-students-show" >
</div >
<div class="student-name">
<h3>Student: <%= @student.name%></h3>
<h3>Grade: <%= @student.grade%></h3>
</div>
<hr class="dotted">

<div class="kudo">
    <% @student.kudos.each do |kudo|%>
    <h4 class="italic-kudo">👏 <%= kudo.kudo%> </h4><br>
    <h5>Teacher: <%= link_to kudo.teacher.teacher_name, teacher_path(kudo.teacher)%></h5>
    <h5>Room: <%= kudo.teacher.room %></h5>
    <h5> Subject: <%= kudo.teacher.subject%></h5><hr class="hr">

    <%end%>

</div>

app/views/teachers/new.erb
<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
<div class="signup">
    <h1>Sign Up!</h1>

    <% if @errors %>
    <% @errors.each do |error| %>
        <%= error %><br>
    <% end %>
    <% end %>

    <%= form_for @teacher do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <br>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
        <%= f.label :teacher %>
        <%= f.text_field :teacher_name %>
        <br>
        <%= f.label :subject %>
        <%= f.text_field :subject %>
        <br>
        <%= f.label :room %>
        <%= f.number_field :room %>
        <br>
        <%=f.submit class:"button"%><br>

        
        
    <%end%>
    </div>
</div>

app/views/teachers/show.erb
<%=  link_to "Home", students_path,class:"home"%>

<div class="space-teachers-show" >
</div >


<div class="teacher-name">
    <h3 style="text-align: center">Teacher: <%=  @teacher.teacher_name%><h3>

    <h3 style="text-align: center">Class: <%= @teacher.subject%></h3>
    <h3 style="text-align: center">Room Number: <%= @teacher.room%></h3>
</div>
<hr class="dotted">

<div class="kudo">
    <% @teacher.kudos.each do |kudo|%>
    <h4>👏 <%= kudo.kudo%> 👏</h4>
    <h5>Student: <%= kudo.student.name%></h5>
    <h5>Grade: <%= kudo.student.grade%></h5>
    <%= button_to "Edit Kudos", edit_kudo_path(kudo), :method => "get", class:"button"%>
    <%= button_to "Delete Kudos", kudo, :method => "delete",params:{'teacher[id]' => @teacher.id}, class:"button2" %>
    <hr class="hr">

    <%end%>
</div>

app/views/users/new.erb
<h1>Sign up</h1>
 
<%= form_with model: @user, html: { class: "form"} do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<br>

<%=f.submit "Login"%>

<%end%>